### ISSUE TITLE
Bug with Deathmessage on Discord

### ISSUE THREAD

**Issue by NoltoxGit** [Winds-Studio/DeathMessages#130]
Hello,
When I enable the `Remove-Plugin-Prefix: true` in the `Messages.yml`. I noticed that part of the message no longer appeared in the webhook.

## Screen about the InGame message:
![image](https://github.com/user-attachments/assets/2e7e2d5f-0eb8-4881-bb37-b7db2fe85d6c)

## Screen about the Discord message with the setting enable:
![image](https://github.com/user-attachments/assets/13e56244-f20c-40a3-ba00-05d69174b100)

## Screen about the Discord message with the setting disable:
![image](https://github.com/user-attachments/assets/71e7c84c-8da4-42b2-8ea3-a0d48840c705)
----
There is my config about this part:
```yml
  DeathMessage:
    Remove-Plugin-Prefix: true
    # Besides the color, you can leave all this blank if you want.
    Color: RED
    # NEW: this was how the old DMP had messages formatted (Playerhead - IconURL, Name - the death message)
    Author:
      # The message of the author
      Name: ''
      # The clickable link
      URL: ''
      # The picture that shows up in the author name
      # Placeholders: %uuid%, %username%
      Icon-URL: ''
    Title: ':skull_crossbones: » NOUVELLE MORT !'
    Description: '%message%'
    Image: 'https://starlightskins.lunareclipse.studio/render/dead/%username%/full?cameraPosition={"x":"35","y":"10","z":"38"}'
    # Block title|Block value|inline boolean
    # To have no content, set content to 'Content: []'
    Content: []
    Footer:
      Text: '%player_display% est mort !'
      Icon-URL: https://heavencube.fr/storage/img/hc512.webp
    Timestamp: true
    Text: ''
 ```
