### ISSUE TITLE
witherskeleton.solo.weapon glitch

### ISSUE THREAD

**Issue by homerek111** [Winds-Studio/DeathMessages#191]
### Checklist

- [x] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [x] I am using latest dev build from https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

### What behaviour is observed?

![Image](https://github.com/user-attachments/assets/3dd270ff-2390-4408-ad72-19c98ede5783)

but i have it defined in config:
```
  witherskeleton:
    Solo:
      Projectile-Arrow:
      - '&c» #07D26F%player% ☠ #86F3BEzginął od #4ACF8EWither Szkieleta'
      Weapon:
      - '&c» #07D26F%player% ☠ #86F3BEzginął od #4ACF8EWither Szkieleta'
      Melee:
      - '&c» #07D26F%player% ☠ #86F3BEzginął od #4ACF8EWither Szkieleta'
    Gang:
      Projectile-Arrow:
      - '&c☠ &c%player% &8Został zabity przez &c%killer%'
      Weapon:
      - '&c☠ &c%player% &8Został zabity przez &c%killer%'
      Melee:
      - '&c☠ &c%player% &8Został zabity przez &c%killer%'
```

### Expected behaviour

-

### To Reproduce

-

### Spark profiler link

-

### Error log (if applicable)

-

**Comment by homerek111** [comment]
latest version from spigot - modern 1.4.20

**Comment by homerek111** [comment]
also 1 more bug - cavespider config does not trigger config values - it used player deathmessage instead of defined one for that specific mob


![Image](https://github.com/user-attachments/assets/3be22774-d69d-47e0-90ff-5b8c80c5c8b2)
it used name defined in /plugins/DeathMessages/Messages.yml + message from player kill instead of 

```
  cavespider:
    Solo:
      Projectile-Arrow:
      - '&c» #07D26F%player% ☠ #86F3BEzginął od #4ACF8EPająka jaskiniowego'
      Weapon:
      - '&c» #07D26F%player% ☠ #86F3BEzginął od #4ACF8EPająka jaskiniowego'
      Melee:
      - '&c» #07D26F%player% ☠ #86F3BEzginął od #4ACF8EPająka jaskiniowego'
    Gang:
      Projectile-Arrow:
      - '&c☠ &c%player% &8Został zabity przez &c%killer%'
      Weapon:
      - '&c☠ &c%player% &8Został zabity przez &c%killer%'
      Melee:
      - '&c☠ &c%player% &8Został zabity przez &c%killer%'
```

from /plugins/DeathMessages/PlayerDeathMessages.yml
